
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import Sidebar from "@/components/sidebar/Sidebar";
import Providers from "@/lib/providers";

import dynamic from "next/dynamic";

const DynamicScrollComponent = dynamic(() => import("@/components/LocomotiveScrollComponent"), { ssr: false });

const jetbrainsMono = JetBrains_Mono({
  weights: [100, 200, 300, 400, 500, 600, 700, 800],
  subsets: ["latin"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Providers>
          <div className="relative min-h-screen h-full w-full">
            <Sidebar />
            {/* <StairTransition /> */}
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
